### ISSUE TITLE
OpenSSL.SSL.Error from imapclient

### ISSUE THREAD

**Issue by wangeek** [magopian/mailbot#6]
Hi, there. When i try to login mail server with ssl =True, I meet this:
```
Traceback (most recent call last):
  File "main.py", line 103, in <module>
    mailbot = MailBot('imap.xxx.com', 'xxx@xxx.com', ******',ssl=True)
  File "E:\Python27\lib\site-packages\mailbot\mailbot.py", line 33, in __init__
    ssl=ssl, stream=stream)
  File "E:\Python27\lib\site-packages\imapclient\imapclient.py", line 152, in __init__
    self._imap = self._create_IMAP4()
  File "E:\Python27\lib\site-packages\imapclient\imapclient.py", line 164, in _create_IMAP4
    self._timeout)
  File "E:\Python27\lib\site-packages\imapclient\tls.py", line 171, in __init__
    imaplib.IMAP4.__init__(self, host, port)
  File "E:\Python27\lib\imaplib.py", line 173, in __init__
    self.open(host, port)
  File "E:\Python27\lib\site-packages\imapclient\tls.py", line 177, in open
    self.sock = wrap_socket(sock, self.ssl_context, host)
  File "E:\Python27\lib\site-packages\imapclient\tls.py", line 144, in wrap_socket
    ssl_context = create_default_context()
  File "E:\Python27\lib\site-packages\imapclient\tls.py", line 127, in create_default_context
    context.load_verify_locations(cadata=certs)
  File "E:\Python27\lib\site-packages\backports\ssl\core.py", line 654, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "E:\Python27\lib\site-packages\OpenSSL\SSL.py", line 685, in load_verify_locations
    _raise_current_error()
  File "E:\Python27\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: []
```
On System: win 10 64bit
Runtime: Python 2.7.13

At last, I found a solution from stackoverflow  [imapClient error (diff version python and windows)](https://stackoverflow.com/a/35046977) which require the old version of imapClient.

**Comment by magopian** [comment]
Hi, I'm sorry I'm not maintaining this project anymore, if you'd like to give it a go, I can add you as a maintainer?
